services:
#  mysql:
#    image: 'mysql:latest'
#    container_name: 'zibview-mysql'
#    environment:
#      - 'MYSQL_DATABASE=zibview'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=zibview'
#    ports:
#      - '3306'
  redis:
    container_name: 'zibview-redis'
    image: 'redis:latest'
    ports:
      - '6379'
