server:
  port: 8080

spring:
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 10

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "314851364329-cv8j0eaveudo1j8klchhfju37bbnv2do.apps.googleusercontent.com"
            client-secret: "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"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging:
  level:
    org:
      springframework:
#        data: DEBUG
#        jdbc: TRACE
#        security: TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

okta:
  oauth2:
    issuer: "https://dev-yqvrvh36brvqbhfs.jp.auth0.com/"
    client-id: "QDbCe5lwg9082thCdd3UtGztaByOUvGW"
    client-secret: "v4eI3Mfqh_PNgp3dAjx0senLINkBaqTpv1r0fiLrhwZMm9B9gSLlD-x7ZxEXiaHN"
    audience: "http://172.30.1.11:8080"

storage:
  root-path: "/home/hyunha/assets"

api:
  zibview:
    url: "http://localhost:8080"
  v-world:
    # 국토교통부_건축물대장정보 서비스
    search-url: "http://apis.data.go.kr/1613000/BldRgstService_v2/getBrTitleInfo"
    key: "NCKyydWNoee4IfwdGytXuM0yQRz1qRX4XrAlIaQxZtntAsERmPPoQINfbRkP6wY3dlAxoJwKXDiML%2B9DSjizqQ%3D%3D"
  juso: # 도로명주소 검색 API 개발 ( 사용기간 : 2024-05-12 ~ 2024-08-10 )
    key: "devU01TX0FVVEgyMDI0MDUxMjIxNTMwNTExNDc2MDE="
  kakao-address:
    key: "621124221ea0da0251f6a56f3b07abc3"
    url: "https://dapi.kakao.com/v2/local"
  kakao-map:
    key: "2042098be1474377a755ca5d4c6e114d"
  naver:
#   url: "https://openapi.naver.com/v1/datalab/search"
    client-id: "JYN395DVGxCzm73TZXU3"
    client-secret: "JYN395DVGxCzm73TZXU3"