server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "${SPRING_PROFILES_ACTIVE}"

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${DATASOURCE_URL}"
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: "${DDL_AUTO}"
    properties:
      default_batch_fetch_size: 10

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}"
            client-secret: "${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging:
  level:
    org:
      springframework:
#        jdbc: TRACE
#        security: TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

okta:
  oauth2:
    issuer: "${OKTA_ISSUER}"
    client-id: "${OKTA_CLIENT_ID}"
    client-secret: "${OKTA_CLIENT_SECRET}"
    audience: "${OKTA_AUDIENCE}"

storage:
  root-path: "${STORAGE_ROOT_PATH}"

api:
  zibview:
    url: "http://localhost:8080"
  v-world:
    search-url: "https://api.vworld.kr"
    key: "${API_VWORLD_KEY}"
  juso: # 도로명주소 검색 API 개발 ( 사용기간 : 2024-05-12 ~ 2024-08-10 )
    key: "${API_JUSO_KEY}"
  kakao-address:
    key: "${API_KAKAO_ADDRESS_KEY}"
    url: "${API_KAKAO_ADDRESS_URL}"
  kakao-map:
    key: "${API_KAKAO_MAP_KEY}"