server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zibview?serverTimezone=Asia/Seoul
    username: root
    password: 1234

logging:
  level:
    org:
      springframework:
#        jdbc: TRACE
#        security: TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

okta:
  oauth2:
    issuer:
    client-id:
    client-secret:
    audience:

storage:
  root-path: "/home/hyunha/dev/assets"

