server:
  port: 8080

spring:
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 10

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

logging:
  level:
    org:
      springframework:
#        data: DEBUG
#        jdbc: TRACE
#        security: TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

okta:
  oauth2:
    issuer:
    client-id:
    client-secret:
    audience:

storage:
  root-path: "/home/hyunha/assets"

api:
  zibview:
    url: "http://localhost:8080"
  v-world:
    # 국토교통부_건축물대장정보 서비스
    search-url: "http://apis.data.go.kr/1613000/BldRgstService_v2/getBrTitleInfo"
    key:
  juso: # 도로명주소 검색 API 개발 ( 사용기간 : 2024-05-12 ~ 2024-08-10 )
    key:
  kakao-address:
    key:
    url: "https://dapi.kakao.com/v2/local"
  kakao-map:
    key:
  naver:
#   url: "https://openapi.naver.com/v1/datalab/search"
    client-id:
    client-secret: